
const questions = [
  {
    question: "Which of the following best defines leadership?",
    options: ["Giving orders to followers", "Influencing others to achieve a common goal", "Controlling employees strictly", "Doing all the work yourself"],
    answer: 1
  },
  {
    question: "What is the primary purpose of self-assessment in leadership?",
    options: ["To compare yourself to others", "To identify personal leadership strengths and weaknesses", "To rank team members", "To impress supervisors"],
    answer: 1
// Pool of 100 unique FBLA Organizational Leadership questions
const questionPool = [
  {question:"Which of the following best defines leadership?", options:["Giving orders to followers","Influencing others to achieve a common goal","Controlling employees strictly","Doing all the work yourself"], answer:1},
  {question:"What is the primary purpose of self-assessment in leadership?", options:["To compare yourself to others","To identify personal leadership strengths and weaknesses","To rank team members","To impress supervisors"], answer:1},
  {question:"Which characteristic is essential for leaders to handle unexpected challenges?", options:["Resiliency","Strictness","Wealth","Popularity"], answer:0},
  {question:"Initiative in leadership refers to:", options:["Waiting for instructions","Taking action without being asked","Delegating all work","Avoiding risk"], answer:1},
  {question:"Leaders who maintain a positive attitude are more likely to:", options:["Lower team morale","Inspire and motivate their followers","Avoid taking responsibility","Focus only on rules"], answer:1},
  {question:"Which is an interpersonal role for managerial leadership?", options:["Figurehead","Spokesperson","Negotiator","Monitor"], answer:0},
  {question:"Which is an informational role for managerial leadership?", options:["Leader","Disseminator","Liaison","Entrepreneur"], answer:1},
  {question:"What is a primary function of a leader as a decision-maker?", options:["Assign tasks only","Solve problems and allocate resources","Watch employees","Avoid conflicts"], answer:1},
  {question:"A manager acting as a liaison is primarily:", options:["Communicating with people inside and outside the organization","Approving paperwork","Monitoring attendance","Focusing on finances"], answer:0},
  {question:"Which is an example of the entrepreneurial role of leadership?", options:["Hiring employees","Developing new initiatives and improvements","Giving presentations","Scheduling meetings"], answer:1},
  {question:"In the communication process, the sender is responsible for:", options:["Interpreting feedback","Creating and sending the message","Ignoring the receiver","Documenting errors"], answer:1},
  {question:"The receiver in communication:", options:["Encodes the message","Decodes and interprets the message","Designs new goals","Avoids feedback"], answer:1},
  {question:"Feedback in communication:", options:["Is optional","Helps the sender know if the message was understood","Only occurs in emails","Is only for criticism"], answer:1},
  {question:"Nonverbal communication includes all EXCEPT:", options:["Facial expressions","Tone of voice","Written reports","Gestures"], answer:2},
  {question:"Active listening requires:", options:["Interrupting to give your opinion","Paying attention, asking clarifying questions, and reflecting","Ignoring body language","Focusing on your own response"], answer:1},
  {question:"What is the main purpose of a team leader?", options:["To control every task","To guide the team toward common goals","To work alone","To delegate all responsibility"], answer:1},
  {question:"Ethical leadership primarily focuses on:", options:["Following rules only","Making decisions that are right and fair","Ignoring consequences","Winning at all costs"], answer:1},
  {question:"LMX theory emphasizes:", options:["Relationship quality between leader and each member","Strictly following hierarchy","Using rewards to motivate","Punishing poor performance"], answer:0},
  {question:"Which skill is critical for resolving conflicts in teams?", options:["Active listening","Ignoring issues","Dictating solutions","Avoiding difficult conversations"], answer:0},
  {question:"Delegation is important because:", options:["It reduces leadership responsibility","It empowers team members and distributes work","It avoids decision-making","It eliminates mistakes"], answer:1},
  {question:"A team with low trust is likely to:", options:["Perform at high levels","Have poor communication and low morale","Exceed expectations","Be fully autonomous"], answer:1},
  {question:"Motivation in leadership is best achieved by:", options:["Ignoring team needs","Understanding team needs and encouraging growth","Using fear as a tool","Giving unclear instructions"], answer:1},
  {question:"Conflict in teams should be:", options:["Ignored","Managed constructively","Amplified to identify problems","Handled by removing team members"], answer:1},
  {question:"A positive leader-member relationship results in:", options:["Lower engagement","Higher productivity and satisfaction","More absenteeism","Less accountability"], answer:1},
  {question:"Time management in leadership is important because:", options:["It ensures deadlines are met","It makes leaders popular","It avoids all conflict","It replaces planning"], answer:0},
  {question:"Effective leaders respond to ambiguity by:", options:["Panicking","Analyzing and adapting","Avoiding responsibility","Following the exact same procedure always"], answer:1},
  {question:"Follow-through in leadership means:", options:["Completing commitments and tasks","Starting projects and ignoring them","Delegating everything","Only doing easy tasks"], answer:0},
  {question:"Which is an example of positive reinforcement?", options:["Ignoring mistakes","Praising a team member for good performance","Punishing errors","Giving unclear feedback"], answer:1},
  {question:"A leader demonstrating ethics:", options:["Cuts corners to save time","Acts with honesty, fairness, and responsibility","Focuses on personal gain","Avoids accountability"], answer:1},
  {question:"Resiliency allows a leader to:", options:["Recover quickly from setbacks","Avoid making decisions","Delegate all work","Ignore team concerns"], answer:0},
  {question:"Building team cohesion involves:", options:["Encouraging collaboration and trust","Isolating team members","Giving orders only","Avoiding communication"], answer:0},
  {question:"Positive attitude in leadership influences:", options:["Only the leader's mood","Team morale and engagement","Nothing significant","Only deadlines"], answer:1},
  {question:"A leader's confidence is shown by:", options:["Indecisiveness","Making informed decisions and standing by them","Avoiding risks","Blaming others"], answer:1},
  {question:"An effective follow-up involves:", options:["Checking progress and giving feedback","Micromanaging every step","Avoiding communication","Punishing mistakes"], answer:0},
  {question:"Successful leaders are able to:", options:["Function independently and make decisions","Rely entirely on others for direction","Avoid responsibility","Ignore challenges"], answer:0},
  {question:"LMX theory divides team members into:", options:["In-group and out-group","High-performers only","Followers only","Groups based on seniority"], answer:0},
  {question:"The main purpose of conflict negotiation is to:", options:["Resolve disputes constructively","Win at all costs","Ignore disagreements","Separate team members"], answer:0},
  {question:"Nonverbal cues include:", options:["Body language, facial expressions, tone of voice","Only emails","Written instructions","Task lists"], answer:0},
  {question:"Feedback should be:", options:["Timely, specific, and constructive","Delayed and vague","Ignored","Always negative"], answer:0},
  {question:"Decision-making in leadership requires:", options:["Analysis, evaluation, and choosing the best option","Ignoring alternatives","Following orders blindly","Only considering personal preferences"], answer:0},
  {question:"Communication barriers include:", options:["Noise, assumptions, unclear messages","Active listening","Eye contact","Feedback"], answer:0},
  {question:"Effective leaders handle ambiguity by:", options:["Remaining flexible and adapting","Avoiding decisions","Delegating all choices","Following rigid rules only"], answer:0},
  {question:"Team building improves:", options:["Cohesion, trust, and productivity","Only communication","Only deadlines","Nothing"], answer:0},
  {question:"A leader’s ethics affect:", options:["Team culture and trust","Only their salary","Nothing","Personal hobbies"], answer:0},
  {question:"A leader functioning independently is able to:", options:["Take initiative and make decisions without constant guidance","Ignore responsibilities","Delegate everything","Avoid working"], answer:0},
  {question:"LMX in-group members usually:", options:["Have higher trust and more responsibilities","Get excluded","Receive fewer opportunities","Are ignored"], answer:0},
  {question:"LMX out-group members usually:", options:["Have limited interaction and less influence","Are highly trusted","Lead major projects","Have more responsibilities"], answer:0},
  {question:"Ethical dilemmas require leaders to:", options:["Consider fairness, honesty, and consequences","Do nothing","Only think about personal gain","Ignore the rules"], answer:0},
  {question:"A leader’s initiative is shown by:", options:["Proactively taking action","Waiting for direction","Delegating all tasks","Avoiding responsibility"], answer:0},
  {question:"Listening skills help leaders:", options:["Understand team concerns and make informed decisions","Ignore feedback","Avoid communication","Delegate everything"], answer:0},
  {question:"Follow-through ensures:", options:["Tasks are completed and commitments are honored","Projects are abandoned","Deadlines are missed","Team morale drops"], answer:0},
  {question:"Resilient leaders:", options:["Bounce back from challenges quickly","Ignore problems","Avoid making decisions","Delegate everything"], answer:0},
  {question:"Positive attitude affects:", options:["Team motivation and workplace culture","Nothing","Only deadlines","Only leadership approval"], answer:0},
  {question:"Time management in leadership ensures:", options:["Effective planning, prioritization, and meeting deadlines","Avoiding work","Only personal success","Ignoring tasks"], answer:0},
  {question:"Active listening requires:", options:["Focusing fully on the speaker, asking questions, reflecting","Interrupting","Ignoring body language","Thinking about your own answer"], answer:0},
  {question:"Conflict negotiation aims to:", options:["Resolve disputes constructively","Escalate issues","Ignore team concerns","Punish mistakes"], answer:0},
  {question:"Team motivation is achieved by:", options:["Understanding needs, setting goals, recognizing achievements","Ignoring team members","Using fear tactics","Overloading work"], answer:0},
  {question:"Communication effectiveness depends on:", options:["Clear messaging, feedback, and understanding barriers","Ignoring the receiver","Random messages","Micromanaging"], answer:0},
  {question:"A leader’s confidence is shown by:", options:["Making informed decisions and standing by them","Doubting constantly","Avoiding responsibility","Delegating everything"], answer:0},
  {question:"Delegation is important because:", options:["It empowers team members and distributes work fairly","It avoids leadership responsibilities","It confuses the team","It increases conflict"], answer:0},
  {question:"Ethical leadership includes:", options:["Honesty, integrity, fairness","Ignoring consequences","Cheating for results","Punishing team members unfairly"], answer:0},
  {question:"LMX relationships improve:", options:["Team trust, satisfaction, and performance","Nothing","Team size","Deadlines only"], answer:0},
  {question:"Leadership involves:", options:["Influencing, guiding, and motivating others","Doing everything alone","Avoiding decisions","Ignoring team input"], answer:0},
  {question:"Feedback should always be:", options:["Constructive and actionable","Delayed and vague","Only negative","Ignored"], answer:0},
  {question:"Time management affects:", options:["Productivity and stress levels","Team size","Nothing","Salary only"], answer:0},
  {question:"Follow-through prevents:", options:["Incomplete tasks and lost trust","Team meetings","Reports","Communication"], answer:0},
  {question:"Team cohesion leads to:", options:["Better collaboration, morale, and performance","Individual work only","Conflict","Missed deadlines"], answer:0},
  {question:"Decision-making requires:", options:["Evaluating options and selecting the best solution","Ignoring alternatives","Delegating all decisions","Following no plan"], answer:0},
  {question:"Positive reinforcement includes:", options:["Praising success and effort","Punishing errors","Ignoring effort","Criticizing always"], answer:0},
  {question:"Resiliency helps leaders:", options:["Overcome setbacks and adapt","Avoid responsibility","Delegate everything","Ignore challenges"], answer:0},
  {question:"Initiative is demonstrated by:", options:["Proactively addressing problems","Waiting for instructions","Delegating all work","Avoiding tasks"], answer:0},
  {question:"Ethical decisions consider:", options:["Fairness, honesty, and consequences","Personal gain only","Rules only","Popularity"], answer:0},
  {question:"Conflict should be:", options:["Managed constructively","Ignored","Escalated","Punished"], answer:0},
  {question:"Nonverbal communication includes:", options:["Body language, facial expressions, tone","Emails only","Reports","Tasks"], answer:0},
  {question:"A leader’s attitude impacts:", options:["Team motivation and engagement","Nothing","Deadlines only","Team size"], answer:0},
  {question:"LMX theory focuses on:", options:["Leader-member relationship quality","Tasks only","Deadlines only","Rewards only"], answer:0},
  {question:"Active listening helps:", options:["Understand team concerns","Ignore feedback","Avoid tasks","Delegate everything"], answer:0},
  {question:"Effective communication includes:", options:["Clear message, feedback, and barrier awareness","Ignoring feedback","Random communication","Micromanaging"], answer:0},
  {question:"Team trust results in:", options:["Higher collaboration and performance","Lower productivity","More absenteeism","Conflict"], answer:0},
  {question:"Motivation in leadership is achieved by:", options:["Understanding and recognizing team needs","Using fear tactics","Ignoring team","Overloading work"], answer:0},
  {question:"Ethics in leadership influences:", options:["Team culture and decision-making","Only deadlines","Nothing","Salary"], answer:0},
  {question:"Follow-through ensures:", options:["Commitments are completed","Tasks are abandoned","Deadlines are missed","Conflict rises"], answer:0},
  {question:"Time management allows leaders to:", options:["Prioritize tasks and meet deadlines","Avoid work","Delegate everything","Ignore tasks"], answer:0},
  {question:"Confidence in leadership is shown by:", options:["Informed decisions and assertiveness","Doubt","Avoiding responsibility","Delegating everything"], answer:0},
  {question:"Resilient leaders:", options:["Recover quickly and adapt","Avoid decisions","Ignore problems","Delegate all work"], answer:0},
  {question:"Team building improves:", options:["Cohesion, trust, performance","Deadlines only","Nothing","Communication only"], answer:0},
  {question:"Decision-making is based on:", options:["Analysis, evaluation, and choice","Guessing","Ignoring options","Avoiding decisions"], answer:0},
  {question:"Feedback should be:", options:["Timely, constructive, and specific","Delayed and vague","Ignored","Negative only"], answer:0},
  {question:"Communication barriers include:", options:["Noise, assumptions, unclear messages","Active listening","Feedback","Eye contact"], answer:0},
  {question:"Conflict negotiation aims to:", options:["Resolve disputes constructively","Escalate conflict","Ignore problems","Punish team members"], answer:0},
  {question:"Positive attitude affects:", options:["Team morale, engagement, and productivity","Nothing","Deadlines only","Leader only"], answer:0},
  {question:"Delegation empowers:", options:["Team members and distributes workload","Leader only","Confuses team","Avoids responsibility"], answer:0},
  {question:"Ethical leadership demonstrates:", options:["Honesty, fairness, integrity","Ignoring consequences","Cheating","Punishing"], answer:0},
  {question:"LMX in-group members:", options:["Have more trust and responsibility","Are ignored","Have fewer opportunities","Are excluded"], answer:0},
  {question:"LMX out-group members:", options:["Have less trust and fewer opportunities","Are highly trusted","Lead projects","Have more responsibilities"], answer:0}
];

// Function to randomly pick up to 100 questions for a quiz
function getRandomQuestions(max=100) {
  let shuffled = [...questionPool].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, Math.min(max, shuffled.length));
}

// Example usage:
// const quizQuestions = getRandomQuestions(100);
// console.log(quizQuestions);
